[project]
name = "gs-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "LGPL-3.0-or-later"
requires-python = ">=3.10"
dependencies = [
    "websockets>=15.0.1"
]
