[project]
name = "mpcc"
version = "0.1.0"
description = "Model Predictive Contouring Control for Even Flow"
readme = "README.md"
authors = [
    { name = "Jasper Day", email = "jromanoday@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
mpcc = "mpcc:main"

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"
